### ISSUE TITLE
Error due to slight name variation between York and RMP websites

### ISSUE THREAD

**Issue by unforgettableid** [mahfoozm/YorkURMP#3]
Hi!  If a professor has a slightly different name on the [York Courses website](https://w2prod.sis.yorku.ca/Apps/WebObjects/cdm) and the Rate My Professors (RMP) website, YorkURMP returns an error.

For example:  York calls one professor "Thomas R Klassen".  Rate My Professors calls him [Thomas Klassen](https://www.ratemyprofessors.com/professor/41108).

YorkURMP reports:  "Error:  this professor is not registered on RateMyProfessors."  I think the issue here is the middle initial.

It would be great if you could please prevent such errors from happening.  One possible workaround might be to trigger a [Google advanced search](https://www.google.ca/advanced_search) of the entire ratemyprofessors.com website, and then for YorkURMP to link to the top Google search result with a link such as "May be Thomas Klassen".

If the top Google hit is a non-York RMP professor, you could label the link with some text such as "May be Tom Klassen from Ryerson University".

A similar issue has been reported [on Reddit](https://www.reddit.com/r/yorku/comments/102qjeo/made_a_ratemyprofessors_extension_for_the_york/j2vjuw6/?context=99).  Clearly, YorkURMP is not the only tool which has had this issue.

As that reporter pointed out, Stephanie Pugliese Domenikos is the same professor as Stephanie Pugliese.  :)

P.S.  Thank you very much for creating YorkURMP and releasing it as open source!  Despite any imperfections, the extension is definitely still helpful.

**Comment by mahfoozm** [comment]
thank you for creating this issue! unfortunately it isn't trivial to do an advanced search as the extension is querying RMP's graphQL API and it expects the professors exact name. however, I pushed a quick and dirty fix (that seems to be very effective) that searches a professors name without their middle name/initial if the initial search does not return any results. it's still awaiting approval on the chrome web store, but you can try it out [now](https://github.com/mahfoozm/YorkURMP/releases/download/v1.1.0/YorkURMP_Chrome.zip) (see instructions for loading unpacked chrome extensions). let me know if you face any issues with this version!

**Comment by unforgettableid** [comment]
Appreciated!  I've tried it, and it's better.  It was definitely able to find ratings for Dr. Klassen.

**Comment by unforgettableid** [comment]
> unfortunately it isn't trivial to do an advanced search as the extension is querying RMP's graphQL API and it expects the professors exact name

Agreed!

It might be necessary to:

1.  Do a Google advanced Web search of the RMP website.
2.  Take note of the exact professor name from the top Google hit.
3.  Do a RMP GraphQL query for that exact name.

Also, this might not be free.  Each API key for the Google Custom Search JSON API only lets you do 100 daily search queries for free.  Additional requests cost half a cent per query.  [(Source.)](https://developers.google.com/custom-search/v1/overview)  I guess you could collect donations, but who knows whether or not people will donate.

Maybe there's some other Web search engine which allows searches for free.  I haven't looked into the matter.

**Comment by mahfoozm** [comment]
> Also, this might not be free. Each API key for the Google Custom Search JSON API only lets you do 100 daily search queries for free. 

i'm afraid this is the biggest issue in implementing something like this, 100 daily requests would be taken up very quickly with the number of requests currently being sent (especially when using VSB)

on top of this, it would be quite an expensive operation to do this whereas it's very lightweight as is

for now, the best solution (unfortunately) is hacky workarounds like searching without a middle name if the initial search returns no results
