### ISSUE TITLE
YorkURMP doesn't show ratings for Glendon profs

### ISSUE THREAD

**Issue by unforgettableid** [mahfoozm/YorkURMP#6]
Hi!  YorkURMP is unable to show ratings for Glendon professors.

See, for example, GL/PSYC 3600 3.00 Psychology and Law with Dr. Stephanie Marion.  YorkURMP says "this professor is not registered on RateMyProfessors" even though she actually [is registered](https://www.ratemyprofessors.com/professor/2613891).

The problem stems from the fact that York's Keele and Glendon campuses are considered separate institutions on the RMP website.  Maybe we should write to the company and ask them to merge the campuses, though unfortunately that would also cause the [campus ratings](https://www.ratemyprofessors.com/school/12125) to be merged as well.

If you decide to do an extra query for the same professor name at Glendon, and the query doesn't find anyone:  Please consider also doing bonus queries for the same professor name at [TMU](https://www.ratemyprofessors.com/school/1471) and [U of T](https://www.ratemyprofessors.com/school/12184) as well.  Profs sometimes change jobs and move around between the various schools in Toronto.

Thank you for reading this!

**Comment by mahfoozm** [comment]
the extension will now search through 4 different school IDs: york (both keele and glendon), TMU, and UofT (sg). let me know if you face any issues with the latest release!

**Comment by unforgettableid** [comment]
Tested.  Verified fixed.  Appreciated!
